apply plugin: 'com.android.application'
android {
    compileSdkVersion 29
    defaultConfig {
        applicationId 'com.ceco.r.gravitybox'
        minSdkVersion 29
        //noinspection OldTargetApi
        targetSdkVersion 29
    }
    buildTypes {
        debug {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'),
                    'proguard-rules.pro'
        }
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android.txt'),
                    'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    lintOptions {
        checkReleaseBuilds false
        abortOnError false
    }
    productFlavors {
    }
}

dependencies {
    compileOnly 'de.robv.android.xposed:api:82'
    implementation 'com.google.android.material:material:1.2.1'
    implementation 'androidx.palette:palette:1.0.0'
    implementation 'com.vanniktech:android-image-cropper:4.7.0'
}
